<a href="https://colab.research.google.com/github/matog/la_heladera_del_chelo/blob/main/chelo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
import cv2
# from google.colab.patches import cv2_imshow
# read input
img = cv2.imread("chelo.jpg")

# specify desired output size 
width = 350
height = 350

# specify conjugate x,y coordinates (not y,x)
input = np.float32([[62,71], [418,59], [442,443], [29,438]])
output = np.float32([[0,0], [90,0], [90,295], [0,286]])

# compute perspective matrix
matrix = cv2.getPerspectiveTransform(input,output)

print(matrix.shape)
print(matrix)

# do perspective transformation setting area outside input to black
imgOutput = cv2.warpPerspective(img, matrix, (width,height), cv2.INTER_LINEAR, borderMode=cv2.BORDER_CONSTANT, borderValue=(0,0,0))
print(imgOutput.shape)

# save the warped output
cv2.imwrite("poster_heladera.jpg", imgOutput)

# show the result
# cv2.imshow("result", imgOutput)
cv2.waitKey(0)
cv2.destroyAllWindows()

(3, 3)
[[ 2.65719260e-01  2.38930124e-02 -1.81709980e+01]
 [ 3.15435920e-02  9.35793230e-01 -6.83970220e+01]
 [ 5.14859029e-05  4.46787311e-04  1.00000000e+00]]
(350, 350, 3)
